## Learn Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create & Read

#### 1D Array

In [12]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(6,)

In [15]:
arr1.dtype

dtype('int64')

In [16]:
arr1.ndim

1

In [17]:
arr1.size

6

#### 2D Array

In [18]:
arr2 = np.array([[1,4,5], [6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [19]:
arr2.ndim

2

In [22]:
arr2.shape #row, col

(2, 3)

In [23]:
arr2.dtype

dtype('int64')

In [24]:
arr2.size

6

#### 3D Array

In [29]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[3,5,4], [8,1,2]], [[1,2,3], [8,9,4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [8, 1, 2]],

       [[1, 2, 3],
        [8, 9, 4]]])

In [30]:
arr3.ndim

3

In [31]:
arr3.shape

(3, 2, 3)

In [32]:
arr3.size

18

### Create random arrays

In [33]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.58155667, 0.57489435, 0.90591169],
        [0.33964335, 0.79807442, 0.78735919]],

       [[0.83575893, 0.37615851, 0.23525249],
        [0.57743874, 0.41470872, 0.02713649]],

       [[0.69695595, 0.77919023, 0.69304454],
        [0.29515978, 0.2451244 , 0.71395572]]])

In [34]:
randomArr.dtype

dtype('float64')

In [35]:
randomArr.shape

(3, 2, 3)

In [40]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [42]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [8, 1, 2]],

       [[1, 2, 3],
        [8, 9, 4]]])

In [49]:
arr3[2,1,1]

np.int64(9)

In [50]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [51]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [8, 1, 2]]])

In [52]:
arr3[-1]

array([[1, 2, 3],
       [8, 9, 4]])

In [53]:
arr3[1,0,1]

np.int64(5)

In [54]:
arr3[1][0][1]

np.int64(5)

## Update & Delete

In [63]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)
a1

array([[[0.3557166 , 0.60848414],
        [0.88800041, 0.17656715],
        [0.33085136, 0.98675416]],

       [[0.85306434, 0.6856525 ],
        [0.79313041, 0.8901351 ],
        [0.0055479 , 0.36678715]]])

In [64]:
a2

array([[[0.22975718, 0.80371559],
        [0.62933841, 0.1086982 ],
        [0.60350385, 0.10130204]],

       [[0.45155686, 0.52398351],
        [0.91346143, 0.05033916],
        [0.62279477, 0.3317716 ]]])

#### Basic Math operations

In [65]:
np.add(a1,a2)

array([[[0.58547378, 1.41219974],
        [1.51733882, 0.28526535],
        [0.93435522, 1.08805621]],

       [[1.3046212 , 1.20963601],
        [1.70659184, 0.94047426],
        [0.62834267, 0.69855875]]])

In [67]:
np.subtract(a1,a2)

array([[[ 0.12595942, -0.19523145],
        [ 0.258662  ,  0.06786896],
        [-0.27265249,  0.88545212]],

       [[ 0.40150748,  0.16166899],
        [-0.12033102,  0.83979594],
        [-0.61724687,  0.03501554]]])

In [68]:
np.divide(a1,a2)

array([[[1.54822847e+00, 7.57088889e-01],
        [1.41100623e+00, 1.62437978e+00],
        [5.48217485e-01, 9.74071322e+00]],

       [[1.88916262e+00, 1.30853832e+00],
        [8.68269178e-01, 1.76827563e+01],
        [8.90807527e-03, 1.10554111e+00]]])

In [69]:
np.multiply(a1,a2)

array([[[0.08172844, 0.48904819],
        [0.55885276, 0.01919253],
        [0.19967007, 0.09996021]],

       [[0.38520706, 0.3592706 ],
        [0.72449404, 0.04480865],
        [0.0034552 , 0.12168956]]])

#### Statistical Operations

In [70]:
sqrt = np.sqrt(25)
abs1 = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [71]:
sqrt

np.float64(5.0)

In [72]:
abs1

np.int64(2)

In [73]:
power

np.int64(256)

In [74]:
log

np.float64(3.2188758248682006)

In [75]:
mins

np.float64(0.005547902694999052)

In [76]:
maxs

np.float64(0.9134614320815292)

#### Update

In [77]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [8, 1, 2]],

       [[1, 2, 3],
        [8, 9, 4]]])

In [80]:
arr3[0,0,2] = 12
arr3

array([[[ 1,  4, 12],
        [ 6,  7,  4]],

       [[ 3,  5,  4],
        [ 8,  1,  2]],

       [[ 1,  2,  3],
        [ 8,  9,  4]]])

In [81]:
arr3.sort()
arr3

array([[[ 1,  4, 12],
        [ 4,  6,  7]],

       [[ 3,  4,  5],
        [ 1,  2,  8]],

       [[ 1,  2,  3],
        [ 4,  8,  9]]])

In [82]:
arr3.shape

(3, 2, 3)

In [87]:
arr3_reshaped = arr3.reshape(1,-1,2) # -1 Allows you to leave one of the dimensions as a variable that the reshape formula will 
                                     # calculate in order to place all of the items
arr3_reshaped

array([[[ 1,  4],
        [12,  4],
        [ 6,  7],
        [ 3,  4],
        [ 5,  1],
        [ 2,  8],
        [ 1,  2],
        [ 3,  4],
        [ 8,  9]]])

#### Appending & Inserting

In [88]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [89]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [92]:
appd = np.append(zeros, ones, axis=0) #axis 0 = row, axis 1 = col
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [93]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [94]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [101]:
instd_arr = np.insert(zeros, 1, ones, axis=0)
instd_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [103]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.79183093, 0.32436778, 0.01615257],
        [0.78042777, 0.03581871, 0.61194395]],

       [[0.75627232, 0.41963175, 0.04507293],
        [0.65572024, 0.02380037, 0.06715782]],

       [[0.27048426, 0.58826117, 0.37827333],
        [0.70226559, 0.91140747, 0.35087951]]])

In [104]:
arr4_del = np.delete(arr4, 0, axis=1)
arr4_del

array([[[0.78042777, 0.03581871, 0.61194395]],

       [[0.65572024, 0.02380037, 0.06715782]],

       [[0.70226559, 0.91140747, 0.35087951]]])

##### Save

In [105]:
np.save("arr4_del", arr4_del)

##### Load

In [108]:
arr4_1 = np.load("arr4_del.npy")
arr4_1

array([[[0.78042777, 0.03581871, 0.61194395]],

       [[0.65572024, 0.02380037, 0.06715782]],

       [[0.70226559, 0.91140747, 0.35087951]]])